app:
 listen: :8081
 storePath: "uploads/file" # 本地上传文件的路径
 host: "https://9kuai8coffee.asia"
#
default:
 wx:
  #appid: wxa4bc935c9ba87528
  #secret: 368ce6cfeeee84764a694ff1cd2ef9ea
  appid: wxf9be667c59929008 
  secret: ff7ab953f4a349d401cae151ca51b42e


sysUser:
  domain: "9kuai8coffee.asia"
  username: "admin"
  password: "123456"

upload:
 oss-type: "local"
 local:
  path: uploads/file
  store-path: uploads/file

db:
 user: root
 password: PASS
 host: 47.98.186.186
 port: 3306
 database: bee_local
 drop: false #是否清之前的数据
 needInit: false #是否需要初始化数据
