app:
 listen: :8081
 storePath: "uploads/file" # 本地上传文件的路径

default:
 wx:
  appid: wxa4bc935c9ba87528
  secret: 368ce6cfeeee84764a694ff1cd2ef9ea
 sysUser:
  domain: "9kuai8coffee.asia"
  username: bee
  password: 123456

upload:
 oss-type: "local"
 local:
  path: uploads/file
  store-path: uploads/file

db:
 user: root
 password: PASS
 host: 127.0.0.1
 port: 3306
 database: bee2
 drop: true #是否清之前的数据
 needInit: true #是否需要初始化数据
