// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package bee

import (
	"time"
)

const TableNameBeeUserMemberCardUseLog = "bee_user_member_card_use_log"

// BeeUserMemberCardUseLog 用户-会员卡使用记录
type BeeUserMemberCardUseLog struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserCardID int32     `gorm:"column:user_card_id;comment:用户-会员卡 表id" json:"user_card_id"` // 用户-会员卡 表id
	UseTime    time.Time `gorm:"column:use_time;comment:使用时间" json:"use_time"`               // 使用时间
}

// TableName BeeUserMemberCardUseLog's table name
func (*BeeUserMemberCardUseLog) TableName() string {
	return TableNameBeeUserMemberCardUseLog
}
